### ISSUE TITLE
Total freeze of Kivy application

### ISSUE THREAD

**Issue by jegger** [rtsh/garden.cefpython#24]
After a while browsing, the application freezes. Not just the browser, also the kivy loop seems blocked. No error / crash.

I can't reproduce the issue yet but it happens from time to time in all applications where this garden.cefpython is used.

**Comment by rtsh** [comment]
does it occur in wxpython, too? Did you check RAM usage maybe?

**Comment by jegger** [comment]
==> Can be solved by removing all print statements. Does only happen when launched in a subprocess.
