### ISSUE TITLE
start url can't be "about:blank"

### ISSUE THREAD

**Issue by jegger** [rtsh/garden.cefpython#7]
If the start-url is about:blank, the back/forward functions won't work properly after loading the first real site.
=> Maybe bug in CEF / CEFPython

Reproduce: 
- In examples/controls.py / .kv gets the URL set after the creation of the browser-class => about:blank gets set. 
- If you browser the web now, you can't use go_back()

If you change "about:blank" to a url in cefbrowser.py it will work.

**Comment by rtsh** [comment]
seems to work now, e.g. in tabbed.py
